<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
namespace Plugin\Admin\Datasource\Configuration;

use Atlas\Orm\Table\AbstractTable;

/**
 * @inheritdoc
 */
class ConfigurationTable extends AbstractTable
{
    /**
     * @inheritdoc
     */
    public function getName()
    {
        return 'configurations';
    }

    /**
     * @inheritdoc
     */
    public function getColNames()
    {
        return [
            'id',
            'plugin',
            'data',
            'active',
            'created_at',
            'updated_at',
        ];
    }

    /**
     * @inheritdoc
     */
    public function getCols()
    {
        return [
            'id' => (object) [
                'name' => 'id',
                'type' => 'integer',
                'size' => null,
                'scale' => null,
                'notnull' => false,
                'default' => null,
                'autoinc' => true,
                'primary' => true,
            ],
            'plugin' => (object) [
                'name' => 'plugin',
                'type' => 'varchar',
                'size' => 255,
                'scale' => null,
                'notnull' => false,
                'default' => null,
                'autoinc' => false,
                'primary' => false,
            ],
            'data' => (object) [
                'name' => 'data',
                'type' => 'text',
                'size' => null,
                'scale' => null,
                'notnull' => true,
                'default' => '{}',
                'autoinc' => false,
                'primary' => false,
            ],
            'active' => (object) [
                'name' => 'active',
                'type' => 'boolean',
                'size' => null,
                'scale' => null,
                'notnull' => true,
                'default' => null,
                'autoinc' => false,
                'primary' => false,
            ],
            'created_at' => (object) [
                'name' => 'created_at',
                'type' => 'datetime',
                'size' => null,
                'scale' => null,
                'notnull' => false,
                'default' => null,
                'autoinc' => false,
                'primary' => false,
            ],
            'updated_at' => (object) [
                'name' => 'updated_at',
                'type' => 'datetime',
                'size' => null,
                'scale' => null,
                'notnull' => false,
                'default' => null,
                'autoinc' => false,
                'primary' => false,
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function getPrimaryKey()
    {
        return [
            'id',
        ];
    }

    /**
     * @inheritdoc
     */
    public function getAutoinc()
    {
        return 'id';
    }

    /**
     * @inheritdoc
     */
    public function getColDefaults()
    {
        return [
            'id' => null,
            'plugin' => null,
            'data' => '{}',
            'active' => null,
            'created_at' => null,
            'updated_at' => null,
        ];
    }
}
